Tasks Micro Service [WIP] 🚧
brunosilvasensedia/mentoria-prog-2023 pull request #6
Opened 2023-11-24 21:01 UTC by edward-mn

### Atividades 

> Os tópicos que consegui finalizar até esse momento, é voltado apenas para as operações de listagem para as futuras tarefas, então por esse motivo ainda deixei o PR como WIP, pois preciso desenvolver o lado das Tarefas.

- Crie um novo projeto Spring Boot chamado "TaskMS", utilizando o template disponível em https://github.com/brunosilvasensedia/mentoria-prog-2023/tree/develop/code/mentoriaprogramacao/mentoriaprogramacao -> ✅

- Adicione as dependências necessárias, como Spring Web e Spring Data JPA. -> ✅
- Crie uma classe Task para representar as tarefas. -> ✅
- Crie uma classe TaskController para expor a entrada de informações através endpoints da API REST para manipular tarefas  (Hexagonal - inbound)-> ✅
- Forneça endpoints para criar, listar e gerenciar tarefas associadas a uma tarefa específica conforme https://github.com/brunosilvasensedia/mentoria-prog-2023/blob/develop/api/todolist-mentoria-api.yml -> ✅
- Crie uma classe TaskService para as regras de negócio (Hexagonal - domain) -> ✅
- Crie uma classe TaskRepository para propiciar a saída de informações através da gravação em base de dados (Hexagonal - outbound) -> ✅
- Configure a entidade User para associar cada tarefa a um usuário específico usando relacionamentos de banco de dados (por exemplo, ManyToOne). -> 🚧

![image](https://github.com/brunosilvasensedia/mentoria-prog-2023/assets/33128259/81c5bcd2-646b-4d77-be96-b306e036fab1)

2023-12-27 14:56 UTC, brunosilvasensedia requested changes
por favor realizar as alterações assinaladas @edward-mn

2023-12-27 14:56 UTC, brunosilvasensedia commented on .vscode/settings.json
favor adicionar os arquivos de configuração ao .gitignore, não iremos manter mais arquivos de configurações específicos de IDE versionados no git.

2023-12-27 14:56 UTC, brunosilvasensedia commented on code/taskMS/.mvn/wrapper/maven-wrapper.jar
não versionar, não é necessário.

2023-12-27 14:56 UTC, brunosilvasensedia commented on code/taskMS/.mvn/wrapper/maven-wrapper.properties
não versionar, não é necessário.

2023-12-27 14:56 UTC, brunosilvasensedia commented on code/taskMS/mvnw
não versionar, não é necessário.

2023-12-27 14:56 UTC, brunosilvasensedia commented on code/taskMS/src/main/resources/application.properties
falar com o luan para substituir estas configuração pela URI que ficará nas variáveis de ambiente.

2023-12-28 18:32 UTC, edward-mn commented on code/taskMS/src/main/resources/application.properties
@brunosilvasensedia Já deixei configurado de forma correta, só não adicionei meu IP lá no Atlas ainda

2023-12-29 18:12 UTC, brunosilvasensedia approved these changes

2023-12-29 18:12 UTC, merged